// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RulesEngine8.Models;

#nullable disable

namespace RulesEngine8.Migrations
{
    [DbContext(typeof(RulesEngineDBContext))]
    [Migration("20240418145430_add Tables")]
    partial class addTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RulesEngine8.Models.ConfigItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConfigItems");
                });

            modelBuilder.Entity("RulesEngine8.Models.HistoryTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("assetUUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailRecipient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("emailSent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HistoryTables");
                });

            modelBuilder.Entity("RulesEngine8.Models.SensorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("alarmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("alarmStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAlarm")
                        .HasColumnType("bit");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("timestampLocal")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("RulesEngine8.Models.ConfigItemModel", b =>
                {
                    b.OwnsOne("RulesEngine8.Models.ConfigJson", "Config", b1 =>
                        {
                            b1.Property<int>("ConfigItemModelId")
                                .HasColumnType("int");

                            b1.Property<string>("email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("longDescription")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("sendEmail")
                                .HasColumnType("bit");

                            b1.Property<string>("shortDescription")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ConfigItemModelId");

                            b1.ToTable("ConfigItems");

                            b1.ToJson("Config");

                            b1.WithOwner()
                                .HasForeignKey("ConfigItemModelId");
                        });

                    b.Navigation("Config")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
