// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RulesEngine8.Models;

#nullable disable

namespace RulesEngine8.Migrations
{
    [DbContext(typeof(RulesEngineDBContext))]
    partial class RulesEngineDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RulesEngine8.Models.ConfigItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigitalInputsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConfigItems");
                });

            modelBuilder.Entity("RulesEngine8.Models.DI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfigItemID")
                        .HasColumnType("int");

                    b.Property<int>("DIIndex")
                        .HasColumnType("int");

                    b.Property<bool>("Error")
                        .HasColumnType("bit");

                    b.Property<string>("ErrorMsg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstallationKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstallationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Invert")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAlarm")
                        .HasColumnType("bit");

                    b.Property<string>("LastTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NumChannels")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Send")
                        .HasColumnType("bit");

                    b.Property<bool>("SendOnChange")
                        .HasColumnType("bit");

                    b.Property<string>("SensorKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SensorType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("alarmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isTPST")
                        .HasColumnType("bit");

                    b.Property<string>("longDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("sendEmail")
                        .HasColumnType("bit");

                    b.Property<string>("shortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("topColor")
                        .HasColumnType("bigint");

                    b.Property<int>("topIndex")
                        .HasColumnType("int");

                    b.Property<bool>("topIsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ConfigItemID");

                    b.ToTable("DigitalInputs");
                });

            modelBuilder.Entity("RulesEngine8.Models.HistoryTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("alarmId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("assetId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailRecipient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("emailSent")
                        .HasColumnType("bit");

                    b.Property<bool>("isAlarm")
                        .HasColumnType("bit");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HistoryTables");
                });

            modelBuilder.Entity("RulesEngine8.Models.SensorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("alarmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("alarmStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAlarm")
                        .HasColumnType("bit");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("timestampLocal")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("RulesEngine8.Models.ConfigItem", b =>
                {
                    b.OwnsOne("RulesEngine8.Models.ConfigJson", "Config", b1 =>
                        {
                            b1.Property<int>("ConfigItemId")
                                .HasColumnType("int");

                            b1.Property<string>("email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("sendEmail")
                                .HasColumnType("bit");

                            b1.HasKey("ConfigItemId");

                            b1.ToTable("ConfigItems");

                            b1.ToJson("Config");

                            b1.WithOwner()
                                .HasForeignKey("ConfigItemId");
                        });

                    b.Navigation("Config");
                });

            modelBuilder.Entity("RulesEngine8.Models.DI", b =>
                {
                    b.HasOne("RulesEngine8.Models.ConfigItem", null)
                        .WithMany("DigitalInputs")
                        .HasForeignKey("ConfigItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RulesEngine8.Models.ConfigItem", b =>
                {
                    b.Navigation("DigitalInputs");
                });
#pragma warning restore 612, 618
        }
    }
}
